### ISSUE TITLE
foreign key field name cannot be the same as primary key field name

### ISSUE THREAD

**Issue by stephentu** [radlab/SCADS#11]
if we have

ENTITY A { 
    int a_id,
    int f0
    PRIMARY(a_id)
}

ENTITY B { 
    int b_id,
    FOREIGN KEY a_id REF A
    PRIMARY(b_id)
}

this will generate code for entity B which is not valid. namely, it will create:
    class a_idType extends EntityPart {
      def getSchema(): Schema = Schema.parse("""{"type":"record","name":"AKey","namespace":"","fields":[{"name":"a_id","type":"int"}]}""")
      var a_id:Int = 0
      def flatValues = List(a_id)
      def flatPut(idx: Int, v:Any): Unit = {
        idx match {
          case 0 => a_id = v.asInstanceOf[java.lang.Integer].intValue
        }
      }
      object a_id extends B.a_idType
[...]

where a_id is defined as an object and a var

**Comment by marmbrus** [comment]
I'm not super concerned about edge cases like these unless they are blocking the undergraduates or SCADr.  Hopefully we can replace all of this generated code with classes augmented by your plugin soon.
