### ISSUE TITLE
entities with no value part cannot be created

### ISSUE THREAD

**Issue by stephentu** [radlab/SCADS#12]
if an entity is created w/ no value, such as
ENTITY A {
  int i
  PRIMARY(i)
}

it will not generate valid code. namely, the ValueType for A will contain an empty flatPut method, which looks like:

```
  def flatPut(idx: Int, v:Any): Unit = { 
    idx match {
    }   
  }   
```

**Comment by stephentu** [comment]
i think we can just generate code which throws an exception, namely

idx match {
case _ => throw some exception
}

in this case, but i just want to make sure this is the right thing to do

**Comment by marmbrus** [comment]
Yeah, that sounds like the right thing to do.

**Comment by stephentu** [comment]
done
