### ISSUE TITLE
When foreign key is a primary key, query with [this] fails to compile

### ISSUE THREAD

**Issue by rniwa** [radlab/SCADS#19]
When a table has a primary key consisting of fields at least one of which is a foreign key, compilation fails due to type mismatch.

Error message:
[INFO] Compiling 1 source files to /Users/ryosuke/Documents/RADish/db/target/classes at 1274807342401
[ERROR] /Users/ryosuke/Documents/RADish/db/target/generated-sources/piql/radish3.scala:325: error: type mismatch;
[INFO]  found   : object Account.this.key.site_id
[INFO]  required: edu.berkeley.cs.scads.piql.parser.BoundValue
[INFO]             singleGet("ent_Account", List(username, site_id))
[INFO]                                                     ^
[ERROR] one error found
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] wrap: org.apache.commons.exec.ExecuteException: Process exited with an error: 1(Exit value: 1)

**Comment by rniwa** [comment]
The schema that caused this error is located at http://gist.github.com/413695

**Comment by marmbrus** [comment]
rewrite
