### ISSUE TITLE
Illegal argument but when trying to Queries.allWord

### ISSUE THREAD

**Issue by amfeng** [radlab/SCADS#21]
scala> Queries.allWord
[ERROR StorageHandler] StorageHandler.scala:863(run) ProcessingException
java.lang.IllegalArgumentException: Illegal Capacity: -1
        at java.util.ArrayList.<init>(Unknown Source)
        at edu.berkeley.cs.scads.storage.StorageHandler.edu$berkeley$cs$scads$st
orage$StorageHandler$$mkSchema(StorageHandler.scala:295)
        at edu.berkeley.cs.scads.storage.StorageHandler$Request$$anonfun$1.apply
(StorageHandler.scala:443)
        at edu.berkeley.cs.scads.storage.StorageHandler$Request$$anonfun$1.apply
(StorageHandler.scala:339)
        at edu.berkeley.cs.scads.storage.StorageHandler$Request.run(StorageHandl
er.scala:859)
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(Unknown Source
)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
java.lang.IllegalArgumentException: Illegal Capacity: -1
        at java.util.ArrayList.<init>(Unknown Source)
        at edu.berkeley.cs.scads.storage.StorageHandler.edu$berkeley$cs$scads$st
orage$StorageHandler$$mkSchema(StorageHandler.scala:295)
        at edu.berkeley.cs.scads.storage.StorageHandler$Request$$anonfun$1.apply
(StorageHandler.scala:443)
        at edu.berkeley.cs.scads.storage.StorageHandler$Request$$anonfun$1.apply
(StorageHandler.scala:339)
        at edu.berkeley.cs.scads.storage.StorageHandler$Request.run(StorageHandl
er.scala:859)
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(Unknown Source
)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
[ERROR Namespace] ScadsCluster.scala:653(getPrefix) Invalid return from getPrefi
x request: java.lang.RuntimeException: Remote Exception{"cause": "java.lang.Ille
galArgumentException: Illegal Capacity: -1", "stacktrace": "java.util.ArrayList.
<init>(Unknown Source)
edu.berkeley.cs.scads.storage.StorageHandler.edu$berkeley$cs$scads$storage$Stora
geHandler$$mkSchema(StorageHandler.scala:295)
edu.berkeley.cs.scads.storage.StorageHandler$Request$$anonfun$1.apply(StorageHan
dler.scala:443)
edu.berkeley.cs.scads.storage.StorageHandler$Request$$anonfun$1.apply(StorageHan
dler.scala:339)
edu.berkeley.cs.scads.storage.StorageHandler$Request.run(StorageHandler.scala:85
9)
java.util.concurrent.ThreadPoolExecutor$Worker.runTask(Unknown Source)
java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
java.lang.Thread.run(Unknown Source)"}
res17: Seq[piql.Word] = List()

QUERY allWord
    FETCH Word
    LIMIT 1000 MAX 1000

**Comment by marmbrus** [comment]
rewrite
