### ISSUE TITLE
KeyValueStoreSpec tests wrong semantics for getRange

### ISSUE THREAD

**Issue by stephentu** [radlab/SCADS#25]
it would make sense if getRange(a, b, ...) returned key/value pairs between the range [a, b), since that's our convention. however, this is currently not how it is implemented or tested:

current:
      it("should correctly return ranges") {
        val ns = cluster.getNamespace[IntRec, IntRec]("rangetest")

```
    /* Insert Integers 1-100 */
    (1 to 100).foreach(i => ns.put(IntRec(i),IntRec(i)))

    /* Various range checks */
    ns.getRange(None, None).map(_._1.f1)               should equal(1 to 100)
    ns.getRange(None, IntRec(50)).map(_._1.f1)         should equal(1 to 50) 
    ns.getRange(IntRec(50), None).map(_._1.f1)         should equal(50 to 100)
    ns.getRange(IntRec(10), IntRec(90)).map(_._1.f1)   should equal(10 to 90) 
    ns.getRange(IntRec(-10), None).map(_._1.f1)        should equal(1 to 100)
    ns.getRange(None, IntRec(110)).map(_._1.f1)        should equal(1 to 100)
    ns.getRange(IntRec(-10), IntRec(110)).map(_._1.f1) should equal(1 to 100)
  }   
```

should be:
      it("should correctly return ranges") {
        val ns = cluster.getNamespace[IntRec, IntRec]("rangetest")

```
    /* Insert Integers 1-100 */
    (1 to 100).foreach(i => ns.put(IntRec(i),IntRec(i)))

    /* Various range checks */
    ns.getRange(None, None).map(_._1.f1)               should equal(1 to 100)
    ns.getRange(None, IntRec(50)).map(_._1.f1)         should equal(1 until 50)
    ns.getRange(IntRec(50), None).map(_._1.f1)         should equal(50 to 100)
    ns.getRange(IntRec(10), IntRec(90)).map(_._1.f1)   should equal(10 until 90)
    ns.getRange(IntRec(-10), None).map(_._1.f1)        should equal(1 to 100)
    ns.getRange(None, IntRec(110)).map(_._1.f1)        should equal(1 to 100)
    ns.getRange(IntRec(-10), IntRec(110)).map(_._1.f1) should equal(1 to 100)
  }   
```

**Comment by kraskat** [comment]
agreed! who should do the change?

**Comment by stephentu** [comment]
both of us i guess. its a very simple change on the server side- i can make those changes in the PartitionHandler. but since you are more familiar w/ the client side you should make those changes with QuorumProtocol

**Comment by kraskat** [comment]
ok

**Comment by stephentu** [comment]
tim: i implemented this on the partition handler + changed the test cases.

**Comment by kraskat** [comment]
Great!
Still two tests are failing (the backwards = true) cases. The cause however, seems to be in the PartitionHandler.

**Comment by stephentu** [comment]
this is now fixed. as of my last commit, every test case passes!
