### ISSUE TITLE
delete namespace makes it imposible to recreate namespace.

### ISSUE THREAD

**Issue by marmbrus** [radlab/SCADS#27]
From perf

scala> ScadrCardinalityTest.results.delete

<restart interpreter>

scala> ScadrCardinalityTest.results

 WARNING: Could not find SCADS configuration file to load. 
 Options are:
   (1) Set environmental variable SCADS_CONFIG to the config file path
   (2) Set system property scads.config to the config file path
 Using default values for config.

java.lang.RuntimeException: Can not load empty routing table
    at edu.berkeley.cs.scads.storage.routing.RoutingProtocol$class.loadRoutingTable(RoutingTable.scala:264)
    at edu.berkeley.cs.scads.storage.routing.RoutingProtocol$class.load(RoutingTable.scala:77)
    at edu.berkeley.cs.scads.storage.SpecificNamespace.edu$berkeley$cs$scads$storage$AvroSerializing$$super$load(Serializers.scala:152)
    at edu.berkeley.cs.scads.storage.AvroSerializing$class.load(Serializers.scala:88)
    at edu.berkeley.cs.scads.storage.SpecificNamespace.load(Serializers.scala:152)
    at edu.berkeley.cs.scads.storage.Namespace.loadOrCreate(Namespace.scala:72)
    at edu.berkeley.cs.scads.storage.ScadsCluster.getNamespace(ScadsCluster.scala:83)
    at edu.berkeley.cs.scads.perf.ScadrCardinalityTest$.<init>(ScadrCardinality.scala:...

**Comment by stephentu** [comment]
can you push the perf code? i can't reproduce:

scala> import edu.berkeley.cs.scads.comm._  
import edu.berkeley.cs.scads.comm._

scala> import edu.berkeley.cs.scads.storage._  
import edu.berkeley.cs.scads.storage._

scala> val cluster = TestScalaEngine.getTestCluster  

scala> val ns = cluster.createNamespace[IntRec, IntRec]("testNS", Seq%28%28None, cluster.getAvailableServers%29%29)
INF [20101012-21:17:02.293] comm: Not connected, deferring connection
INF [20101012-21:17:02.366] storage: [<CounterID: 0, EnvDir: /tmp/scads1389331523100491989testdb, Handle: {"num": 0}@gibson:9000>] CreatePartitionRequest for namespace testNS, [null, null)
INF [20101012-21:17:02.395] storage: 1 active partitions after insertion in ZooKeeper
INF [20101012-21:17:02.486] storage: [<CounterID: 0, EnvDir: /tmp/scads1389331523100491989testdb, Handle: {"num": 0}@gibson:9000>] 1 active partitions after insertion on this StorageHandler
INF [20101012-21:17:02.486] storage: Partition testNS0000000000 in namespace testNS created
ns: edu.berkeley.cs.scads.storage.SpecificNamespace[edu.berkeley.cs.scads.comm.IntRec,edu.berkeley.cs.scads.comm.IntRec] = edu.berkeley.cs.scads.storage.SpecificNamespace@1b66659

scala> ns.put(IntRec(1), IntRec(1))

scala> ns.delete

/// restart scala console

scala> import edu.berkeley.cs.scads.comm._  
import edu.berkeley.cs.scads.comm._

scala> import edu.berkeley.cs.scads.storage._  
import edu.berkeley.cs.scads.storage._

scala> val cluster = TestScalaEngine.getTestCluster                                                        

scala> val ns = cluster.createNamespace[IntRec, IntRec]("testNS", Seq%28%28None, cluster.getAvailableServers%29%29)
INF [20101012-21:17:54.141] comm: Not connected, deferring connection
INF [20101012-21:17:54.222] storage: [<CounterID: 0, EnvDir: /tmp/scads740695123160037794testdb, Handle: {"num": 0}@gibson:9000>] CreatePartitionRequest for namespace testNS, [null, null)
INF [20101012-21:17:54.267] storage: 1 active partitions after insertion in ZooKeeper
INF [20101012-21:17:54.352] storage: [<CounterID: 0, EnvDir: /tmp/scads740695123160037794testdb, Handle: {"num": 0}@gibson:9000>] 1 active partitions after insertion on this StorageHandler
INF [20101012-21:17:54.353] storage: Partition testNS0000000000 in namespace testNS created
ns: edu.berkeley.cs.scads.storage.SpecificNamespace[edu.berkeley.cs.scads.comm.IntRec,edu.berkeley.cs.scads.comm.IntRec] = edu.berkeley.cs.scads.storage.SpecificNamespace@6d3209

scala> ns.get(IntRec(1))
res0: Option[edu.berkeley.cs.scads.comm.IntRec] = None

**Comment by marmbrus** [comment]
pushed but please don't try to recreate using perf right now (i'm running experiments and thats where the data is stored)

You need to reuse the same storage engine in order for the bug to manifest:
    scala> TestScalaEngine.getTestCluster
    INF [20101012-21:57:33.092] storage: Opening BDB Environment: /var/folders/j9/j9ypjQyrGhuug4j0G-oyQk+++TI/-Tmp-/scads5734992296839917557testdb, allowCreate=true
    INF [20101012-21:57:33.092] storage: cacheSize=0
    INF [20101012-21:57:33.092] storage: txnNoSync=false
    INF [20101012-21:57:33.092] storage: txnWriteNoSync=false
    INF [20101012-21:57:33.092] storage: {je.env.isTransactional=true, je.maxMemoryPercent=80}
    res0: edu.berkeley.cs.scads.storage.ScadsCluster = edu.berkeley.cs.scads.storage.ScadsCluster@504a89f7

```
scala> res0.getNamespace[IntRec, IntRec]("test")
INF [20101012-21:57:46.540] comm: Connecting to dhcp-45-92.eecs.berkeley.edu/128.32.45.92:9000
INF [20101012-21:57:46.557] comm: Not connected, deferring connection
INF [20101012-21:57:46.600] storage: [<CounterID: 0, EnvDir: /private/var/folders/j9/j9ypjQyrGhuug4j0G-oyQk+++TI/-Tmp-/scads4542398084405397938testdb, Handle: {"num": 0}@dhcp-45-92.eecs.berkeley.edu:9000>] CreatePartitionRequest for namespace test, [null, null)
INF [20101012-21:57:46.621] storage: 1 active partitions after insertion in ZooKeeper
INF [20101012-21:57:46.666] storage: [<CounterID: 0, EnvDir: /private/var/folders/j9/j9ypjQyrGhuug4j0G-oyQk+++TI/-Tmp-/scads4542398084405397938testdb, Handle: {"num": 0}@dhcp-45-92.eecs.berkeley.edu:9000>] 1 active partitions after insertion on this StorageHandler
INF [20101012-21:57:46.666] storage: Partition test0000000000 in namespace test created
res1: edu.berkeley.cs.scads.storage.SpecificNamespace[edu.berkeley.cs.scads.comm.IntRec,edu.berkeley.cs.scads.comm.IntRec] = edu.berkeley.cs.scads.storage.SpecificNamespace@61917b9e

scala> res1.delete
INF [20101012-21:57:52.656] storage: WARNING: About to delete namespace test! All information and metadata will be lost!
INF [20101012-21:57:52.671] comm: delete() - successfully deleted path: /testScads/namespaces/test/partitions/test0000000000
INF [20101012-21:57:52.679] storage: Deleting metadata for partition test0000000000
INF [20101012-21:57:52.695] storage: Successfully deleted namespace test on StorageHandler {"num": 0}@dhcp-45-92.eecs.berkeley.edu:9000
INF [20101012-21:57:52.695] storage: Deleting zookeeper metadata for namespace test
INF [20101012-21:57:52.701] comm: delete() - successfully deleted path: /testScads/namespaces/test/routingtable
INF [20101012-21:57:52.711] comm: delete() - successfully deleted path: /testScads/namespaces/test/quorumProtConfig
INF [20101012-21:57:52.714] comm: delete() - successfully deleted path: /testScads/namespaces/test/partitions
INF [20101012-21:57:52.717] comm: delete() - successfully deleted path: /testScads/namespaces/test/valueSchema
INF [20101012-21:57:52.720] comm: delete() - successfully deleted path: /testScads/namespaces/test/keySchema
INF [20101012-21:57:52.721] comm: delete() - successfully deleted path: /testScads/namespaces/test

scala> res0.getNamespace[IntRec, IntRec]("test")
INF [20101012-21:57:55.533] storage: [<CounterID: 0, EnvDir: /private/var/folders/j9/j9ypjQyrGhuug4j0G-oyQk+++TI/-Tmp-/scads4542398084405397938testdb, Handle: {"num": 0}@dhcp-45-92.eecs.berkeley.edu:9000>] CreatePartitionRequest for namespace test, [null, null)
INF [20101012-21:57:55.552] storage: 1 active partitions after insertion in ZooKeeper
ERR [20101012-21:57:55.577] storage: Exception processing storage request: java.lang.AssertionError: assertion failed: Partition ID was not unique: test0000000000
ERR [20101012-21:57:55.578] storage: scala.Predef$.assert(Predef.scala:91)
ERR [20101012-21:57:55.578] storage: edu.berkeley.cs.scads.storage.StorageHandler.process(StorageHandler.scala:278)
ERR [20101012-21:57:55.578] storage: edu.berkeley.cs.scads.storage.StorageHandler.process(StorageHandler.scala:30)
ERR [20101012-21:57:55.578] storage: edu.berkeley.cs.scads.comm.ServiceHandler$Request.run(MessageReceiver.scala:86)
ERR [20101012-21:57:55.578] storage: java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
ERR [20101012-21:57:55.578] storage: java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
ERR [20101012-21:57:55.578] storage: java.lang.Thread.run(Thread.java:637)
java.lang.RuntimeException: {"cause": "java.lang.AssertionError: assertion failed: Partition ID was not unique: test0000000000", "stacktrace": "scala.Predef$.assert(Predef.scala:91)
edu.berkeley.cs.scads.storage.StorageHandler.process(StorageHandler.scala:278)
edu.berkeley.cs.scads.storage.StorageHandler.process(StorageHandler.scala:30)
edu.berkeley.cs.scads.comm.ServiceHandler$Request.run(MessageReceiver.scala:86)
java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
java.lang.Thread.run(Thread.java:637)"}
    at edu.berkeley.cs.scads.comm.RemoteActorProxy$class.$bang$qmark(Actors.scala:76)
    at edu.berkeley.cs.scads.comm.StorageService.$bang$qmark(Actors.scala:34)
    at edu.berkeley...
```

**Comment by stephentu** [comment]
k, i see why this particular error (the assertion error) is occuring- i forgot to cleanup a map on deletion of namespace. should not be that hard to fix

however, the original error you posted is different from this one, and is not explained immediately by this bug that i just identified. having said that, i wouldn't be surprised if they were related. are you doing anything different to trigger the 1st one?

**Comment by marmbrus** [comment]
Sorry, that shows up the second time you try to get it.  It's because the namespace is partially created so its metadata is invalid.

A namespace creation failure should probably clean up after itself...

**Comment by stephentu** [comment]
k i fixed this particular bug- let me know if it works in perf. i didnt try it b/c i didnt want to blow away your exp data

**Comment by marmbrus** [comment]
Seems to work
