### ISSUE TITLE
AvroRecord has problems with invalid fields

### ISSUE THREAD

**Issue by karlhe** [radlab/SCADS#48]
AvroRecord does some `method_missing?` stuff to read/write from fields. Giving an invalid field using a command such as this:

```
@user.foo
```

Often results in this error:

```
stack level too deep
```

Shouldn't be a problem with good coding, but should probably look into what's causing this.

**Comment by bdon** [comment]
Seems like the simple answer is to increase the JVM's stack size

http://www.caucho.com/resin-3.0/performance/jvm-tuning.xtp

you can pass the -Xss flag into jruby.
