### ISSUE TITLE
Null Pointer Exception when a query returns nothing

### ISSUE THREAD

**Issue by aaronbee** [radlab/SCADS#7]
Queries.userByName("albert", $piql_env)

NativeException: java.lang.NullPointerException: null
    from edu/berkeley/cs/scads/piql/queryexecution.scala:135:in `apply'
    from edu/berkeley/cs/scads/piql/queryexecution.scala:133:in`apply'
    from scala/collection/TraversableLike.scala:238:in `apply'
    from scala/collection/TraversableLike.scala:238:in`apply'
    from scala/collection/LinearSeqLike.scala:97:in `foreach'
    from scala/collection/immutable/List.scala:46:in`foreach'
    from scala/collection/TraversableLike.scala:238:in `map'
    from scala/collection/immutable/List.scala:46:in`map'
    from edu/berkeley/cs/scads/piql/queryexecution.scala:133:in `materialize'
    from piql/scadr.scala:554:in`materialize'
    from piql/scadr.scala:568:in `userByName'
    from piql/scadr.scala:-1:in`userByName'

**Comment by stephentu** [comment]
done
